/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package images;

/**
 *
 * @author ASUS
 */
public class TrangChuJPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form TrangChuJPanel
     */
    public TrangChuJPanel() {
       
        initComponents();
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pupTrangChu = new javax.swing.JPopupMenu();
        mnitMoMay = new javax.swing.JMenuItem();
        mnitTatMay = new javax.swing.JMenuItem();
        mnitNapTien = new javax.swing.JMenuItem();
        mnitTinNhan = new javax.swing.JMenuItem();
        HomePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnMay1 = new javax.swing.JLabel();
        btnMay2 = new javax.swing.JLabel();
        btnMay3 = new javax.swing.JLabel();
        btnMay4 = new javax.swing.JLabel();
        btnMay5 = new javax.swing.JLabel();
        btnMay6 = new javax.swing.JLabel();
        btnMay7 = new javax.swing.JLabel();
        btnMay8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnMay9 = new javax.swing.JLabel();
        btnMay10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnMay11 = new javax.swing.JLabel();
        btnMay12 = new javax.swing.JLabel();
        btnMay13 = new javax.swing.JLabel();
        btnMay14 = new javax.swing.JLabel();
        btnMay15 = new javax.swing.JLabel();
        btnMay16 = new javax.swing.JLabel();
        btnMay17 = new javax.swing.JLabel();
        btnMay18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnMay19 = new javax.swing.JLabel();
        btnMay20 = new javax.swing.JLabel();

        mnitMoMay.setText("Mở máy");
        pupTrangChu.add(mnitMoMay);

        mnitTatMay.setText("Tắt máy");
        pupTrangChu.add(mnitTatMay);

        mnitNapTien.setText("Nạp Tiền");
        pupTrangChu.add(mnitNapTien);

        mnitTinNhan.setText("Nhắn tin");
        pupTrangChu.add(mnitTinNhan);

        btnMay1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetCF/images/1.png"))); // NOI18N
        btnMay1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMay1MouseClicked(evt);
            }
        });
        jPanel1.add(btnMay1);

        btnMay2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetCF/images/2.png"))); // NOI18N
        btnMay2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMay2MouseClicked(evt);
            }
        });
        jPanel1.add(btnMay2);

        btnMay3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetCF/images/3.png"))); // NOI18N
        btnMay3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMay3MouseClicked(evt);
            }
        });
        jPanel1.add(btnMay3);

        btnMay4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetCF/images/4.png"))); // NOI18N
        btnMay4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMay4MouseClicked(evt);
            }
        });
        jPanel1.add(btnMay4);

        btnMay5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetCF/images/5.png"))); // NOI18N
        btnMay5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMay5MouseClicked(evt);
            }
        });
        jPanel1.add(btnMay5);

        btnMay6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetCF/images/6.png"))); // NOI18N
        btnMay6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMay6MouseClicked(evt);
            }
        });
        jPanel1.add(btnMay6);

        btnMay7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetCF/images/7.png"))); // NOI18N
        btnMay7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMay7MouseClicked(evt);
            }
        });
        jPanel1.add(btnMay7);

        btnMay8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetCF/images/8.png"))); // NOI18N
        btnMay8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMay8MouseClicked(evt);
            }
        });
        jPanel1.add(btnMay8);
        jPanel1.add(jPanel2);

        btnMay9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetCF/images/9.png"))); // NOI18N
        btnMay9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMay9MouseClicked(evt);
            }
        });
        jPanel1.add(btnMay9);

        btnMay10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetCF/images/10.png"))); // NOI18N
        btnMay10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMay10MouseClicked(evt);
            }
        });
        jPanel1.add(btnMay10);

        btnMay11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetCF/images/11.png"))); // NOI18N
        btnMay11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMay11MouseClicked(evt);
            }
        });
        jPanel3.add(btnMay11);

        btnMay12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetCF/images/12.png"))); // NOI18N
        btnMay12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMay12MouseClicked(evt);
            }
        });
        jPanel3.add(btnMay12);

        btnMay13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetCF/images/13.png"))); // NOI18N
        btnMay13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMay13MouseClicked(evt);
            }
        });
        jPanel3.add(btnMay13);

        btnMay14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetCF/images/14.png"))); // NOI18N
        btnMay14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMay14MouseClicked(evt);
            }
        });
        jPanel3.add(btnMay14);

        btnMay15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetCF/images/15.png"))); // NOI18N
        btnMay15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMay15MouseClicked(evt);
            }
        });
        jPanel3.add(btnMay15);

        btnMay16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetCF/images/16.png"))); // NOI18N
        btnMay16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMay16MouseClicked(evt);
            }
        });
        jPanel3.add(btnMay16);

        btnMay17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetCF/images/17.png"))); // NOI18N
        btnMay17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMay17MouseClicked(evt);
            }
        });
        jPanel3.add(btnMay17);

        btnMay18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetCF/images/18.png"))); // NOI18N
        btnMay18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMay18MouseClicked(evt);
            }
        });
        jPanel3.add(btnMay18);
        jPanel3.add(jPanel5);

        btnMay19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetCF/images/19.png"))); // NOI18N
        btnMay19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMay19MouseClicked(evt);
            }
        });
        jPanel3.add(btnMay19);

        btnMay20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NetCF/images/20.png"))); // NOI18N
        btnMay20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMay20MouseClicked(evt);
            }
        });
        jPanel3.add(btnMay20);

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMay1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMay1MouseClicked
        // TODO add your handling code here:
        pupTrangChu.show(btnMay1, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnMay1MouseClicked

    private void btnMay2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMay2MouseClicked
        pupTrangChu.show(btnMay2, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnMay2MouseClicked

    private void btnMay3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMay3MouseClicked
        pupTrangChu.show(btnMay3, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnMay3MouseClicked

    private void btnMay4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMay4MouseClicked
        pupTrangChu.show(btnMay4, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnMay4MouseClicked

    private void btnMay5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMay5MouseClicked
       pupTrangChu.show(btnMay5, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnMay5MouseClicked

    private void btnMay6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMay6MouseClicked
        pupTrangChu.show(btnMay6, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnMay6MouseClicked

    private void btnMay7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMay7MouseClicked
        pupTrangChu.show(btnMay7, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnMay7MouseClicked

    private void btnMay8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMay8MouseClicked
       pupTrangChu.show(btnMay8, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnMay8MouseClicked

    private void btnMay9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMay9MouseClicked
        pupTrangChu.show(btnMay9, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnMay9MouseClicked

    private void btnMay10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMay10MouseClicked
        pupTrangChu.show(btnMay10, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnMay10MouseClicked

    private void btnMay11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMay11MouseClicked
        pupTrangChu.show(btnMay11, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnMay11MouseClicked

    private void btnMay12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMay12MouseClicked
        pupTrangChu.show(btnMay12, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnMay12MouseClicked

    private void btnMay13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMay13MouseClicked
        pupTrangChu.show(btnMay13, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnMay13MouseClicked

    private void btnMay14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMay14MouseClicked
       pupTrangChu.show(btnMay14, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnMay14MouseClicked

    private void btnMay15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMay15MouseClicked
        pupTrangChu.show(btnMay15, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnMay15MouseClicked

    private void btnMay16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMay16MouseClicked
        pupTrangChu.show(btnMay16, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnMay16MouseClicked

    private void btnMay17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMay17MouseClicked
        pupTrangChu.show(btnMay17, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnMay17MouseClicked

    private void btnMay18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMay18MouseClicked
        pupTrangChu.show(btnMay18, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnMay18MouseClicked

    private void btnMay19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMay19MouseClicked
        pupTrangChu.show(btnMay19, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnMay19MouseClicked

    private void btnMay20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMay20MouseClicked
        pupTrangChu.show(btnMay20, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnMay20MouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomePanel;
    private javax.swing.JLabel btnMay1;
    private javax.swing.JLabel btnMay10;
    private javax.swing.JLabel btnMay11;
    private javax.swing.JLabel btnMay12;
    private javax.swing.JLabel btnMay13;
    private javax.swing.JLabel btnMay14;
    private javax.swing.JLabel btnMay15;
    private javax.swing.JLabel btnMay16;
    private javax.swing.JLabel btnMay17;
    private javax.swing.JLabel btnMay18;
    private javax.swing.JLabel btnMay19;
    private javax.swing.JLabel btnMay2;
    private javax.swing.JLabel btnMay20;
    private javax.swing.JLabel btnMay3;
    private javax.swing.JLabel btnMay4;
    private javax.swing.JLabel btnMay5;
    private javax.swing.JLabel btnMay6;
    private javax.swing.JLabel btnMay7;
    private javax.swing.JLabel btnMay8;
    private javax.swing.JLabel btnMay9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JMenuItem mnitMoMay;
    private javax.swing.JMenuItem mnitNapTien;
    private javax.swing.JMenuItem mnitTatMay;
    private javax.swing.JMenuItem mnitTinNhan;
    private javax.swing.JPopupMenu pupTrangChu;
    // End of variables declaration//GEN-END:variables
}
